name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        run: .\tools\premake\bin\premake5.exe vs2019

      - name: Build ${{ matrix.config }} binaries
        run: cd build && msbuild /p:Configuration=${{ matrix.config }} OpenNeighborhood.sln

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xorg-dev
          sudo apt-get install libgtk-3-dev

      - name: Generate project files
        run: ./tools/premake/bin/premake5 gmake2

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate project files
        run: ./tools/premake/bin/premake5_macos gmake2

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}
