name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - run: .\tools\premake\bin\premake5.exe vs2019
      - run: cd build && msbuild /p:Configuration=${{ matrix.config }} OpenNeighborhood.sln

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xorg-dev
          sudo apt-get install libgtk-3-dev
      - run: ./tools/premake/bin/premake5 gmake2
      - run: cd build && make config=${{ matrix.config }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/premake/bin/premake5_macos gmake2
      - run: cd build && make config=${{ matrix.config }}
