name: Build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - run: .\scripts\genprojects-win-vs.bat
      - run: msbuild /p:Configuration=${{ matrix.config }}
      - name: Upload Artifacts
        if: matrix.config == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: OpenNeighborhood-windows
          path: bin\Release\

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xorg-dev
          sudo apt-get install libgtk-3-dev
      - run: ./scripts/genprojects-linux.sh
      - run: make config=${{ matrix.config }}
      - name: Upload Artifacts
        if: matrix.config == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: OpenNeighborhood-linux
          path: bin/Release/

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/genprojects-macos.sh
      - run: make config=${{ matrix.config }}
      - name: Upload Artifacts
        if: matrix.config == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: OpenNeighborhood-macos
          path: bin/Release/
