name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        run: .\scripts\genprojects-win-vs.bat

      - name: Build ${{ matrix.config }} binaries
        run: cd build && msbuild /p:Configuration=${{ matrix.config }} OpenNeighborhood.sln

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y xorg-dev libgtk-3-dev

      - name: Generate project files
        run: ./scripts/genprojects-linux.sh

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate project files
        run: ./scripts/genprojects-macos.sh

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}
